### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by trsh** [pablospe/MVCDemo#3]
"original code provided by authors"

Can't find. Can u give me alink?

**Comment by pablospe** [comment]
They sent me an email with a zip file. The first commit is the original code without modification:
https://github.com/pablospe/MVCDemo/commit/275eead1e92df5bd0371c10d85609a506f7c72b8

**Comment by trsh** [comment]
@pablospe can you send me the zip to janis.taranda@gmail.com pls or point to some other resource, as the commit 275eead hold only a logic for displaying a window :/

I also checked commit named "Original code", but that already holds lot of QT logic, so that ain't also it?

**Comment by pablospe** [comment]
yes, the commit "Original code" is the unzip version of the code I received from the author, which included Qt code/logic.
